# Generated by Django 4.1.3 on 2022-11-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=1200, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=1000, null=True)),
                ('publisher', models.CharField(max_length=1000, null=True)),
                ('pub_date', models.CharField(max_length=10, null=True)),
                ('img_url', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(null=True)),
                ('isbn13', models.CharField(max_length=13, null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
