# Generated by Django 4.1.3 on 2022-11-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=1000, null=True)),
                ('book_author', models.CharField(max_length=1000, null=True)),
                ('year_of_publication', models.CharField(max_length=10, null=True)),
                ('book_publisher', models.CharField(max_length=1000, null=True)),
                ('img_l', models.CharField(max_length=1000, null=True)),
                ('summary', models.CharField(max_length=13, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
