# Generated by Django 4.1.3 on 2022-11-07 06:20


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=1000, null=True)),
                ('book_author', models.CharField(max_length=1000, null=True)),
                ('year_of_publication', models.CharField(max_length=10, null=True)),
                ('book_publisher', models.CharField(max_length=1000, null=True)),
                ('img_l', models.CharField(max_length=1000, null=True)),
                ('summary', models.CharField(max_length=13, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
