# Generated by Django 4.1.3 on 2022-11-07 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorites',
            field=models.ManyToManyField(null=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
